package handler

import (
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"

	"github.com/maccavelli/mcp-server-magictools/internal/db"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

func TestIsGeneratedFile(t *testing.T) {
	tests := []struct {
		name     string
		src      []byte
		expected bool
	}{
		{
			name:     "standard marker",
			src:      []byte("// Code generated by some-tool. DO NOT EDIT."),
			expected: true,
		},
		{
			name:     "no marker",
			src:      []byte("package main\n\nfunc main() {}"),
			expected: false,
		},
		{
			name:     "marker after 1KB",
			src:      append(make([]byte, 1025), []byte("Code generated")...),
			expected: false,
		},
		{
			name:     "DO NOT EDIT marker",
			src:      []byte("// DO NOT EDIT"),
			expected: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isGeneratedFile(tt.src); got != tt.expected {
				t.Errorf("isGeneratedFile() = %v, want %v", got, tt.expected)
			}
		})
	}
}

func TestCountDecls(t *testing.T) {
	tests := []struct {
		name     string
		src      []byte
		expected int
	}{
		{
			name:     "empty package",
			src:      []byte("package test"),
			expected: 0,
		},
		{
			name: "single func",
			src: []byte(`package test
func Hello() {}
`),
			expected: 1,
		},
		{
			name: "multiple decls",
			src: []byte(`package test
type T struct{}
func F() {}
var V = 1
const C = 2
`),
			expected: 4,
		},
		{
			name: "grouped decls",
			src: []byte(`package test
var (
	V1 = 1
	V2 = 2
)
const (
	C1 = 1
	C2 = 2
)
`),
			expected: 4,
		},
		{
			name:     "invalid source",
			src:      []byte("not a valid go source"),
			expected: -1,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := countDecls(tt.src); got != tt.expected {
				t.Errorf("countDecls() = %v, want %v", got, tt.expected)
			}
		})
	}
}

func TestQuickDeclCountCheck(t *testing.T) {
	tests := []struct {
		name     string
		orig     []byte
		mod      []byte
		wantDecr bool
		wantOrig int
		wantMod  int
	}{
		{
			name:     "no change",
			orig:     []byte("package test\nfunc F() {}"),
			mod:      []byte("package test\nfunc F() {}"),
			wantDecr: false,
			wantOrig: 1,
			wantMod:  1,
		},
		{
			name:     "addition",
			orig:     []byte("package test\nfunc F() {}"),
			mod:      []byte("package test\nfunc F() {}\nfunc G() {}"),
			wantDecr: false,
			wantOrig: 1,
			wantMod:  2,
		},
		{
			name:     "removal",
			orig:     []byte("package test\nfunc F() {}\nfunc G() {}"),
			mod:      []byte("package test\nfunc F() {}"),
			wantDecr: true,
			wantOrig: 2,
			wantMod:  1,
		},
		{
			name:     "malformed original",
			orig:     []byte("invalid"),
			mod:      []byte("package test"),
			wantDecr: false,
			wantOrig: 0,
			wantMod:  0,
		},
		{
			name:     "malformed modified",
			orig:     []byte("package test"),
			mod:      []byte("invalid"),
			wantDecr: true,
			wantOrig: 0,
			wantMod:  0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gotDecr, gotOrig, gotMod := quickDeclCountCheck(tt.orig, tt.mod)
			if gotDecr != tt.wantDecr {
				t.Errorf("quickDeclCountCheck() gotDecr = %v, want %v", gotDecr, tt.wantDecr)
			}
			if gotOrig != tt.wantOrig {
				t.Errorf("quickDeclCountCheck() gotOrig = %v, want %v", gotOrig, tt.wantOrig)
			}
			if gotMod != tt.wantMod {
				t.Errorf("quickDeclCountCheck() gotMod = %v, want %v", gotMod, tt.wantMod)
			}
		})
	}
}

func TestApplyASTTransformations(t *testing.T) {
	tests := []struct {
		name        string
		src         []byte
		wantChanged bool
	}{
		{
			name: "missing package doc",
			src: []byte(`package test
`),
			wantChanged: true,
		},
		{
			name: "missing func doc",
			src: []byte(`package test
// Package test provides functionality for the test subsystem.
func Exported() {}
`),
			wantChanged: true,
		},
		{
			name: "missing type doc",
			src: []byte(`package test
// Package test provides functionality for the test subsystem.
type Exported struct{}
`),
			wantChanged: true,
		},
		{
			name: "already has docs",
			src: []byte(`// Package test provides functionality for the test subsystem.
package test

// Exported performs the Exported operation.
func Exported() {}
`),
			wantChanged: false,
		},
		{
			name: "generated file",
			src: []byte(`// Code generated by tool. DO NOT EDIT.
package test
func Exported() {}
`),
			wantChanged: false,
		},
		{
			name:        "invalid source",
			src:         []byte(`invalid go code`),
			wantChanged: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, changed := applyASTTransformations("test.go", tt.src)
			if changed != tt.wantChanged {
				t.Errorf("applyASTTransformations() changed = %v, want %v", changed, tt.wantChanged)
			}
		})
	}
}

func TestGitCheckpoints(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "git-test-*")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmpDir)

	// Ensure git doesn't find a parent git repo (like /home/adm_saxsmith/.git)
	os.Setenv("GIT_CEILING_DIRECTORIES", filepath.Dir(tmpDir))
	defer os.Unsetenv("GIT_CEILING_DIRECTORIES")

	// Test 1: Non-git directory
	checkpoint := createGitCheckpoint(tmpDir, "session-1")
	if checkpoint != "" {
		t.Errorf("expected empty checkpoint for non-git dir, got %q", checkpoint)
	}

	// Setup git repo
	runGit := func(args ...string) {
		cmd := exec.Command("git", args...)
		cmd.Dir = tmpDir
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v failed: %v, output: %s", args, err, string(out))
		}
	}

	runGit("init")
	runGit("config", "user.email", "test@example.com")
	runGit("config", "user.name", "Test User")

	// Test 2: No changes to checkpoint (and no commits yet - git stash push fails)
	checkpoint = createGitCheckpoint(tmpDir, "session-2")
	if checkpoint != "" {
		t.Errorf("expected empty checkpoint for no commits, got %q", checkpoint)
	}

	// Create initial commit
	err = os.WriteFile(filepath.Join(tmpDir, "file.txt"), []byte("initial content"), 0644)
	if err != nil {
		t.Fatal(err)
	}
	runGit("add", "file.txt")
	runGit("commit", "-m", "initial commit")

	// Test 3: No changes after initial commit
	checkpoint = createGitCheckpoint(tmpDir, "session-3")
	if checkpoint != "" {
		t.Errorf("expected empty checkpoint for no changes, got %q", checkpoint)
	}

	// Test 4: Successful checkpoint
	err = os.WriteFile(filepath.Join(tmpDir, "file.txt"), []byte("modified content"), 0644)
	if err != nil {
		t.Fatal(err)
	}

	checkpoint = createGitCheckpoint(tmpDir, "session-4")
	if checkpoint == "" {
		t.Fatal("expected checkpoint name, got empty")
	}

	// Verify it stashed (file.txt should be back to initial content)
	content, _ := os.ReadFile(filepath.Join(tmpDir, "file.txt"))
	if string(content) != "initial content" {
		t.Errorf("expected 'initial content' after stash, got %q", string(content))
	}

	// Test 5: Rollback
	// Modify again
	err = os.WriteFile(filepath.Join(tmpDir, "file.txt"), []byte("corrupted content"), 0644)
	if err != nil {
		t.Fatal(err)
	}
	rollbackGitCheckpoint(tmpDir, checkpoint)

	content, _ = os.ReadFile(filepath.Join(tmpDir, "file.txt"))
	if string(content) != "modified content" {
		t.Errorf("expected 'modified content' after rollback, got %q", string(content))
	}

	// Test 6: Cleanup
	// (Re-checkpoint to have something to drop)
	err = os.WriteFile(filepath.Join(tmpDir, "file.txt"), []byte("new changes"), 0644)
	if err != nil {
		t.Fatal(err)
	}
	checkpoint = createGitCheckpoint(tmpDir, "session-5")
	if checkpoint == "" {
		t.Fatal("expected checkpoint name for session-5")
	}
	cleanupGitCheckpoint(tmpDir)
}

func TestSHA256Hash(t *testing.T) {
	h1 := sha256Hash("test")
	h2 := sha256Hash("test")
	h3 := sha256Hash("other")

	if h1 != h2 {
		t.Error("identical strings should have identical hashes")
	}
	if h1 == h3 {
		t.Error("different strings should have different hashes")
	}
}

func TestHandleExecutePipeline_DryRun(t *testing.T) {
	h, store, _, tmpDir := newTestHandler(t)
	defer os.RemoveAll(tmpDir)
	defer store.Close()

	ctx := context.Background()

	// Enable pipeline gate
	h.PipelineEnabled = &atomic.Bool{}
	h.PipelineEnabled.Store(true)

	// Add some mock tools
	tools := []*db.ToolRecord{
		{
			URN:         "brainstorm:analyzer",
			Name:        "analyzer",
			Server:      "brainstorm",
			Description: "Analyzes and refactors code",
			Role:        "ANALYZER",
			Phase:       1,
		},
		{
			URN:         "go-modernizer:planner",
			Name:        "planner",
			Server:      "go-modernizer",
			Description: "Plans the refactor of the code",
			Role:        "PLANNER",
			Phase:       2,
		},
	}

	for _, tool := range tools {
		if err := store.SaveTool(tool); err != nil {
			t.Fatalf("failed to save tool: %v", err)
		}
	}

	args := map[string]any{
		"target":       tmpDir,
		"session_id":   "test-session-123",
		"intent":       "analyzer and planner for code refactor",
		"dry_run":      true,
		"target_roles": []string{"ANALYZER", "PLANNER"},
	}
	argsJSON, _ := json.Marshal(args)
	req := &mcp.CallToolRequest{
		Params: &mcp.CallToolParamsRaw{},
	}
	req.Params.Arguments = argsJSON

	res, err := h.handleExecutePipeline(ctx, req)
	if err != nil {
		t.Fatalf("handleExecutePipeline failed: %v", err)
	}

	if res.IsError {
		foundErr := ""
		for _, c := range res.Content {
			if tc, ok := c.(*mcp.TextContent); ok {
				foundErr = tc.Text
			}
		}
		t.Fatalf("expected no error, got error: %s", foundErr)
	}

	// Verify content contains a dry run plan
	foundPlan := false
	var fullText strings.Builder
	for _, c := range res.Content {
		if tc, ok := c.(*mcp.TextContent); ok {
			fullText.WriteString(tc.Text)
			if strings.Contains(tc.Text, "# Pipeline Plan for:") {
				foundPlan = true
			}
		}
	}
	if !foundPlan {
		t.Errorf("did not find '# Pipeline Plan for:' in result content. Full output: %s", fullText.String())
	}
}
