package handler

import (
	"context"
	"strings"
	"testing"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

func TestExecutePipelineCoverage(t *testing.T) {
	// 1. buildStepSummaryJSON
	results := []stepResult{
		{
			URN:    "tool1",
			Output: "output1",
			Status: "success",
			Error:  "",
		},
	}
	_ = buildStepSummaryJSON(results)

	// 2. sha256Hash
	_ = sha256Hash("test")

	// 3. enforceContextCap
	var sb strings.Builder
	for range 4000 {
		sb.WriteString("word word word word ")
	}
	_ = enforceContextCap(&sb, "header")

	// small context
	var sbSmall strings.Builder
	sbSmall.WriteString("small string")
	_ = enforceContextCap(&sbSmall, "header")

	// 4. extractTextOutput
	res1 := &mcp.CallToolResult{
		Content: []mcp.Content{&mcp.TextContent{Text: "text output"}},
	}
	extractTextOutput(res1)
	extractTextOutput(nil)

	// 5. extractStagingURI
	extractStagingURI("here is a uri: file:///staging/path/test.go inside text")
	extractStagingURI("no uri here")

	// 6. extractPlanHashFromResults
	resPlan := []stepResult{
		{Output: "plan_hash: 12345"},
	}
	extractPlanHashFromResults(resPlan)

	// 7. isGeneratedFile
	isGeneratedFile([]byte("// Code generated by test. DO NOT EDIT."))
	isGeneratedFile([]byte("package main"))

	// 8. countDecls
	countDecls([]byte(`
package main
func test() {}
type T struct{}
var x int
`))

	// 9. mcpGoBinary
	mcpGoBinary()

	// 10. buildPipelineResult
	buildPipelineResult(results, "success", []string{"warning 1"})

	// 11. composeMutatorStages
	_ = composeMutatorStages()

	// extractTextOutput
	extractTextOutput(&mcp.CallToolResult{Content: nil})

	// isGeneratedFile
	isGeneratedFile([]byte("// Code generated by"))

	// countDecls
	countDecls([]byte("package main\nfunc main() {}"))

	// extractPlanHashFromResults
	extractPlanHashFromResults([]stepResult{
		{Output: "HASH: 12345"},
	})

	// mcpGoBinary
	mcpGoBinary()

	// buildSchemaAwareArgs
	buildSchemaAwareArgs(nil, "urn", "sessionID", "target", "prevOutput")

	// schemaProperties
	schemaProperties(nil, "urn")

	// schemaRequired
	schemaRequired(nil, "urn")

	// savePipelineArtifacts
	savePipelineArtifacts(context.Background(), &OrchestratorHandler{}, "sessionID", nil)

	// validateShadowBuffer
	h := &OrchestratorHandler{}
	h.validateShadowBuffer(context.Background(), "session", "target", nil)

	// executeMutatorAST
	h.executeMutatorAST(context.Background(), nil, "session", "invalid_dir", "hash", "")

	// executeDAGStep
	h.executeDAGStep(context.Background(), nil, PipelineStep{ToolName: "urn"}, "session", "target", "")

	// pipelineGate
	h.pipelineGate()
}
